### ISSUE TITLE
client.close()出现问题

### ISSUE THREAD

**Issue by zhangshuiyong** [reanote/ssdb-node#2]
close() {
        this._waitSend = [];
        for (let conn in this._busyConn){
            conn.close();
        }
        for (let conn in this._idleConn){
            conn.close();
        }
    };

_idleConn和_busyConn是个数组，conn只是index号，应该是_idleConn[conn].close()

**Comment by code-research** [comment]
Thx, 已在5.0.1中修复

**Comment by reanote** [comment]
Thx, 已修复 ver:5.0.1
