### ISSUE TITLE
New commands not available

### ISSUE THREAD

**Issue by YindSoft** [reanote/ssdb-node#3]
Hello.

There are a few commands that are new and I need to use them and the only way is to modify the list of available commands.
So it would be good to update the list, for example I need to use "qrange"
Also would be interesting to set a custom command so you could send any type of command to the server that way if there is something new it can be used right away.

**Comment by reanote** [comment]
Thank you for your suggestion, 
I have been add "qrange" to the commands;
The custom command will be add at next version.
